version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    ports:
      - '8000:8000'
    networks:
      - backend
    tty: true
    depends_on:
      - db
    volumes:
      - $PWD:/home
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile2
    container_name: db
    hostname: db
    ports:
      - '27017:27017'
    networks:
      - backend
#  redis:
#    build:
#      context: .
#      dockerfile: docker/redis/Dockerfile
#    container_name: redis
#    hostname: redis
#    ports:
#      - '6379:6379'
#    networks:
#      - backend

networks:
  backend:
    driver: 'bridge'